[package]
name = "borderlands_damage_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
dirs = "5.0.1"
eframe = "0.27.2"
serde = { version = "1.0.203", features = ["derive"] }
